# Generated by Django 3.2.9 on 2021-12-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('creators', models.TextField()),
                ('cover', models.ImageField(upload_to='', verbose_name='D:\\Users\\Aryan Jassal\\Projects\\DatabaseManagement\\database_management/static/icon_not_found.png')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genres', models.ManyToManyField(to='database.Genres')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('creator', models.TextField()),
                ('cover', models.ImageField(upload_to='', verbose_name='D:\\Users\\Aryan Jassal\\Projects\\DatabaseManagement\\database_management/static/icon_not_found.png')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='database.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('author', models.TextField()),
                ('cover', models.ImageField(upload_to='', verbose_name='D:\\Users\\Aryan Jassal\\Projects\\DatabaseManagement\\database_management/static/icon_not_found.png')),
                ('published_by', models.TextField(blank=True, null=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('isbn', models.IntegerField(max_length=13, null=True)),
                ('genres', models.ManyToManyField(to='database.Genres')),
            ],
        ),
    ]
